processing_weights:
  enabled_methods:
    - GreedyPortfolio
    - LpPortfolio
    - ProportionalRoundingAllocator
    - WeightedFloorAllocator
    - TransactionCostAllocator
    - DiversityAllocator
    - ClusteredAllocator
#    - MinRiskLpPortfolio
#    - ProportionalGreedyPortfolio
#    - CustomGreedyAllocation

  budget: 100000