processing_weights:
  enabled_methods:
    - CustomClusteredAllocator
    - CustomDiversityAllocator
    - CustomProportionalRoundingAllocator
    - CustomTransactionCostAllocator
    - CustomWeightedFloorAllocator
    - GreedyPortfolio
    - LpPortfolio
  budget: 100000